# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

logo-facebook = "https://facebook.com/paezdev/"
logo-twitter = "https://twitter.com/paezdev/"
logo-instagram = "https://instagram.com/paezdev/"
logo-linkedin = "https://www.linkedin.com/in/paezdev/"
logo-github = "https://github.com/paezdev/"
logo-dribbble = "https://dribbble.com/"
# logo-figma = "figma.com/"
logo-youtube = "https://youtube.com/@paezdev/"
# logo-reddit = "https://www.reddit.com/"
# logo-discord = "https://discord.com/"
# logo-pinterest = "https://www.pinterest.com/"